# Generated by Django 5.2.5 on 2025-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="eliminada",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
