# Generated by Django 5.2.5 on 2025-08-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0002_alter_tarea_eliminada"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtarea",
            old_name="tarea_id",
            new_name="id_tarea",
        ),
    ]
