# Generated by Django 5.2.5 on 2025-08-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0003_rename_tarea_id_subtarea_id_tarea"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtarea",
            old_name="id_tarea",
            new_name="tarea",
        ),
    ]
