# Generated by Django 5.2.5 on 2025-08-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0004_rename_id_tarea_subtarea_tarea"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtarea",
            old_name="tarea",
            new_name="tarea_id",
        ),
    ]
