# Generated by Django 5.2.5 on 2025-08-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0005_rename_tarea_subtarea_tarea_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtarea",
            name="tarea_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtareas",
                to="desafioadl.tarea",
            ),
        ),
    ]
